server:
  port: 8101
eureka:
  instance:
    #应用实例主机名
    hostname: peer2
    #客户端在注册时使用自己的IP而不是主机名，默认：false
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    #是否将自己注册到Eureka Server(高可用注册中心的时候要为true)
    register-with-eureka: true
    #是否从Eureka Server获取注册的服务信息,作为服务注册中心，不需要检索服务信息(高可用注册中心的时候要为true)
    fetch-registry: true
    #Eureka服务器的地址，类型为HashMap，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka
    #如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔(这里需要将eureka-availability注册到eureka中)
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
